[project]
name = "reddit-dataplatform-orchestration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "apache-airflow>=3.2.2",
    "apache-airflow-providers-amazon>=9.29.0",
    "apache-airflow-providers-apache-spark>=6.0.2",
    "apache-airflow-providers-dbt-cloud>=4.9.1",
    "mypy>=2.1.0",
    "pyspark>=4.1.2",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.16",
]
